src/Entity/Picture.php
<?php

namespace App\Entity;

use App\Repository\PictureRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PictureRepository::class)
 * @Vich\Uploadable
 */
class Picture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="photos", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tags;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_validated;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): self
    {
        $this->imageFile = $imageFile;
        if ($imageFile !== null) {
            $this->updated_at = new \DateTimeImmutable();
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(?string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Categorie
    {
        return $this->category;
    }

    public function setCategory(?Categorie $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getIsValidated(): ?bool
    {
        return $this->is_validated;
    }

    public function setIsValidated(bool $is_validated): self
    {
        $this->is_validated = $is_validated;

        return $this;
    }
}

src/Controller/PictureController.php
<?php

namespace App\Controller;

use App\Entity\Picture;
use App\Form\UploadPictureType;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PictureController extends AbstractController
{
    /**
     * @Route("/admin/pictures", name="admin_picture")
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {

        $query = $this->getDoctrine()->getRepository(Picture::class)->findAll();

        $page = $request->query->getInt('page', 1);
        $pictures = $paginator->paginate(
            $query,
            $page === 0 ? 1 : $page,
            30
        );

        return $this->render('picture/index.html.twig', [
            'pictures' => $pictures
        ]);
    }

    /**
     * @Route("/admin/pictures/delete/{id}", name="admin_pictures_delete")
     */
    public function delete($id)
    {
        $picture = $this->getDoctrine()->getRepository(Picture::class)->find($id);

        // Si l'image n'existe pas, on retourne une erreur 404
        // Ou si l'image n'appartient pas à l'utilisateur connecté, on retourne une erreur 404C
        if (!$picture) {
            throw $this->createNotFoundException('Cette image n\'existe pas'); // Erreur 404 - Ressource non trouvée
            // throw $this->createAccessDeniedException('Cette image n\'existe pas'); // Erreur 403 - Accès refusé
        }


        $doctrine = $this->getDoctrine()->getManager();
        $doctrine->remove($picture);
        $doctrine->flush();

        $this->addFlash('success', 'La photo à bien été supprimée');

        return $this->redirectToRoute('admin_picture');
    }

    /**
     * @Route("/admin/pictures/edit/{id}", name="admin_pictures_edit")
     */
    public function edit($id, Request $request)
    {
        $picture = $this->getDoctrine()->getRepository(Picture::class)->find($id);

        if (!$picture) {
            throw $this->createNotFoundException('La photo n\'existe pas');
        }

        $formEditPicture = $this->createForm(UploadPictureType::class, $picture, [
            'validation_groups' => 'edit_picture'
        ]);
        $formEditPicture->handleRequest($request);

        if ($formEditPicture->isSubmitted() && $formEditPicture->isValid()) {
            $picture->setCreatedAt(new \DateTimeImmutable());

            $doctrine = $this->getDoctrine()->getManager();
            $doctrine->persist($picture);
            $doctrine->flush();

            $this->addFlash('success', 'La photo a bien été modifié');
            
            return $this->redirectToRoute('admin_picture');
        }     

        return $this->render('picture/edit.html.twig', [
            'formEditPicture' => $formEditPicture->createView()
        ]);
    }
}

templates/picture/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modier une Image
{% endblock %}

{% block body %}

	<h1 class="h3 mb-3 font-weight-bold">Modifie l'image'</h>

	{{ form_start(formEditPicture) }}
	{{ form_rest(formEditPicture) }}
	<button class="btn btn-primary">Modif</button>
	{{ form_end(formEditPicture) }}


{% endblock %}

templates/picture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Administration - Gestion des images
{% endblock %}
{# Ajoute notre javascript #}
{% block javascripts %}
	{{ parent() }}
	{# Récupère les fichiers JS contenu dans le block javascript du fichier base.html.twig #}
	<script src="{{ asset('js/deleteModal.js') }}" defer></script>
{% endblock %}

{% block body %}
	<h1 class="h3 mb-3 font-weight-bold">Admin</h1>

	{# Affiche un message de succès #}
	{% for message in app.flashes('success') %}
		<div class="alert alert-success">{{ message }}</div>
	{% endfor %}

	<table class="table">
		<thead>
			<tr class="table-dark">
				<th>ID</th>
				<th>Aperçu</th>
				<th>Déposé le</th>
				<th>Auteur</th>
				<th>Validé ?</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for picture in pictures %}
				<tr>
					<td>{{ picture.id }}</td>
					<td>
						<img src="{{ asset('uploads/images/photos/'~ picture.image)|imagine_filter('short') }}" alt="{{ picture.image }}" class="rounded">
					</td>
					<td>{{ picture.createdAt|date('d.m.Y') }}</td>
					<td>{{ picture.user.firstname }} {{ picture.user.lastname }}</td>
					<td>{{ picture.isValidated ? 'Validé' : 'Non validé' }}</td>
					<td>
					<a href="{{ path('admin_pictures_edit', {'id': picture.id}) }}" class="btn btn-secondary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                            <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                        </svg>
                    </a>
						<button type="button" data-href="{{ path('admin_pictures_delete', {'id': picture.id}) }}" class="btn btn-danger confirm-delete">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle-fill" viewbox="0 0 16 16">
								<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z"/>
							</svg>
						</td>
					</td>
				</tr>
			</button>
		</tbody>
	</td>
</tr></td></tbody></tr>{% else %}<tr><td class="py-5 text-center text-muted" colspan="4">Aucune catégorie pour le moment :(</td></tr>{% endfor %}</tbody></table>{{ knp_pagination_render(pictures) }}<!-- Modal --><div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="staticBackdropLabel">Suppression</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body">Êtes-vous sûr de vouloir supprimer cette photo ?</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button><a href="" class="btn btn-danger">Oui, je confirme !</a></div></div></div></div>{% endblock %}